export const SET_TOKEN = 'SET_TOKEN'
export const SET_USER_DATA = 'SET_USER_DATA'
export const SET_TASKS_DATA = 'SET_TASKS_DATA'
export const UPDATE_TASKS_DATA = "UPDATE_TASKS_DATA"
export const TOGGLE_FORM_TASK = "TOGGLE_FORM_TASK"
export const UPDATE_TASKDATA = "UPDATE_TASKDATA"
export const FORM_TASKDATA = "FORM_TASKDATA"